name: test_subtraction
on: push
jobs:
  test:
    run-on: ubuntu-latest
    strategy:
      matrix:
        Python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: All test
      run: bash -xv ./test_subtraction.bash


